# Projects are listed alphabetically.

[[projects]]
name = "Aleo"
url = "https://github.com/AleoHQ"
repos = [
"AleoHQ/aleo",
"AleoHQ/snarkOS",
"AleoHQ/snarkVM",
"AleoHQ/leo",
]

[[projects]]
name = "Anoma"
url = "https://github.com/anoma"
repos = [
"anoma/anoma",
"anoma/ferveo",
"anoma/masp",
"anoma/plonkup-hash",
]

[[projects]]
name = "ChainSafe"
url = "https://github.com/ChainSafe"
repos = [
"ChainSafe/forest",
"ChainSafe/filecoindot",
]

[[projects]]
name = "COMIT"
url = "https://github.com/comit-network"
repos = [
"comit-network/maia",
"comit-network/rendezvous-server",
"comit-network/xmr-btc-swap",
"comit-network/xtra-productivity",
"comit-network/waves",
]

[[projects]]
name = "Concordium"
url = "https://github.com/Concordium"
repos = [
"Concordium/concordium-rust-smart-contracts",
"Concordium/concordium-wasm-smart-contracts",
"Concordium/concordium-contracts-common",
"Concordium/concordium-rust-sdk",
"Concordium/concordium-base",
"Concordium/concordium-transaction-logger",
"Concordium/concordium-euro2ccd-service",
"Concordium/concordium-use-case-examples",
"Concordium/concordium-node",
]

[[projects]]
name = "Conflux"
url = "https://github.com/Conflux-Chain"
repos = [
"Conflux-Chain/conflux-rust",
]

[[projects]]
name = "DarkFi"
url = "https://github.com/darkrenaissance/darkfi"
repos = [
"darkrenaissance/darkfi",
]

[[projects]]
name = "Dfinity"
url = "https://github.com/dfinity"
repos = [
"dfinity/ic",
"dfinity/sdk",
"dfinity/agent-rs",
"dfinity/icx-proxy",
"dfinity/cdk-rs",
"dfinity/candid",
"dfinity/quill",
"dfinity/experimental-minting-tool",
"dfinity/vessel",
"dfinity/bitcoin-developer-preview",
"dfinity/ic-types",
]

[[projects]]
name = "Elrond"
url = "https://github.com/ElrondNetwork"
repos = [
"ElrondNetwork/elrond-wasm-rs",
"ElrondNetwork/sc-dex-rs",
"ElrondNetwork/sc-nft-marketplace",
"ElrondNetwork/sc-metabonding-rs",
"ElrondNetwork/sc-bridge-elrond",
"ElrondNetwork/sc-chainlink-rs",
"ElrondNetwork/sc-delegation-rs",
"ElrondNetwork/sc-savings-account-rs",
]

[[projects]]
name = "Espresso Systems"
url = "https://github.com/EspressoSystems"
repos = [
"EspressoSystems/jellyfish",
"EspressoSystems/cape",
"EspressoSystems/reef",
"EspressoSystems/seahorse",
"EspressoSystems/cap",
]

[[projects]]
name = "Findora"
url = "https://github.com/FindoraNetwork"
repos = [
"FindoraNetwork/zei",
"FindoraNetwork/platform",
"FindoraNetwork/findora-scanner",
"FindoraNetwork/bp",
"FindoraNetwork/findora-exporter",
"FindoraNetwork/findorad",
"FindoraNetwork/abcf",
"FindoraNetwork/bs3",
"FindoraNetwork/storage",
]

[[projects]]
name = "Fluence"
url = "https://github.com/fluencelabs"
repos = [
"fluencelabs/marine",
"fluencelabs/aquavm",
"fluencelabs/fluence",
"fluencelabs/examples",
"fluencelabs/registry",
"fluencelabs/trust-graph",
"fluencelabs/aqua-ipfs",
]

[[projects]]
name = "Fuel"
url = "https://github.com/FuelLabs"
repos = [
"FuelLabs/fuel-asm",
"FuelLabs/fuel-bft",
"FuelLabs/fuel-core",
"FuelLabs/fuel-crypto",
"FuelLabs/fuel-merkle",
"FuelLabs/fuel-storage",
"FuelLabs/fuel-tx",
"FuelLabs/fuel-types",
"FuelLabs/fuel-vm",
"FuelLabs/fuels-rs",
"FuelLabs/sway",
]

[[projects]]
name = "Golem"
url = "https://github.com/golemfactory"
repos = [
"golemfactory/ya-runtime-http-auth",
"golemfactory/yagna",
"golemfactory/ya-service-bus",
"golemfactory/ya-client",
"golemfactory/ya-relay",
"golemfactory/ya-runtime-sdk",
"golemfactory/ya-runtime-vm",
"golemfactory/ya-vm-file-server",
]

[[projects]]
name = "Grin"
url = "https://github.com/mimblewimble/grin"
repos = [
"mimblewimble/grin",
"mimblewimble/grin-wallet",
]

[[projects]]
name = "Holochain"
url = "https://github.com/holochain"
repos = [
"holochain/holochain",
"holochain/absquic",
"holochain/launcher",
"holochain/holochain-client-rust",
"holochain/holochain-wasmer",
"holochain/hc-utils",
]

[[projects]]
name = "IOTA"
url = "https://github.com/iotaledger"
repos = [
"iotaledger/bee",
"iotaledger/wallet.rs",
"iotaledger/iota.rs",
"iotaledger/identity.rs",
"iotaledger/cli-wallet",
"iotaledger/streams",
"iotaledger/stronghold.rs",
"iotaledger/chronicle.rs",
]

[[projects]]
name = "MobileCoin"
url = "https://github.com/mobilecoinfoundation"
repos = [
"mobilecoinfoundation/mobilecoin",
"mobilecoinfoundation/mc-oblivious",
"mobilecoinfoundation/fog",
]

[[projects]]
name = "NEAR"
url = "https://github.com/near/nearcore"
repos = [
"near/workspaces-rs",
"near/nearcore",
"near/near-cli-rs",
"near/near-sdk-rs",
"near/near-jsonrpc-client-rs",
"near/near-lake",
"near/near-blake2",
"near/core-contracts",
"near/near-lake-framework",
"near/borsh-rs",
"near/near-indexer-for-explorer",
"near/wasmer",
]

[[projects]]
name = "Nervos"
url = "https://github.com/nervosnetwork"
repos = [
"nervosnetwork/axon",
"nervosnetwork/godwoken",
"nervosnetwork/ckb",
"nervosnetwork/godwoken-scripts",
"nervosnetwork/mercury",
"nervosnetwork/ckb-vm",
"nervosnetwork/godwoken-tests",
"nervosnetwork/ckb-cli",
"nervosnetwork/molecule",
"nervosnetwork/capsule",
"nervosnetwork/ckb-indexer",
"nervosnetwork/overlord",
]

[[projects]]
name = "Oasis"
url = "https://github.com/oasisprotocol"
repos = [
"oasisprotocol/oasis-sdk",
"oasisprotocol/cipher-paratime",
"oasisprotocol/emerald-paratime",
]

[[projects]]
name = "Parity"
url = "https://github.com/paritytech"
repos = [
"paritytech/substrate",
"paritytech/polkadot",
"paritytech/cumulus",
"paritytech/parity-signer",
"paritytech/smoldot",
"paritytech/ink",
"paritytech/parity-common",
"paritytech/subxt",
"paritytech/jsonrpsee",
"paritytech/frontier",
"paritytech/cargo-contract",
"paritytech/substrate-contracts-node",
"paritytech/ink-playground",
"paritytech/metadata-portal",
"paritytech/parity-bridges-common",
]

[[projects]]
name = "Rust Bitcoin"
url = "https://github.com/rust-bitcoin"
repos = [
"rust-bitcoin/rust-bitcoin",
"rust-bitcoin/rust-miniscript",
"rust-bitcoin/rust-bitcoincore-rpc",
"lightningdevkit/rust-lightning",
"lightningdevkit/ldk-sample",
"lightningdevkit/ldk-c-bindings",
]

[[projects]]
name = "Rust Ethereum"
url = "https://github.com/rust-bitcoin"
repos = [
"rust-ethereum/ethabi",
"rust-ethereum/enr",
"rust-ethereum/devp2p",
"rust-ethereum/dnsdisc",
]

[[projects]]
name = "Lighthouse"
url = "https://github.com/sigp/lighthouse"
repos = [
"sigp/lighthouse",
"sigp/discv5",
]

[[projects]]
name = "Secret Network"
url = "https://github.com/scrtlabs"
repos = [
"scrtlabs/SecretNetwork",
"scrtlabs/secret-toolkit",
"scrtlabs/snip20-reference-impl",
]

[[projects]]
name = "Solana"
url = "https://github.com/solana-labs"
repos = [
"solana-labs/solana",
"solana-labs/solana-program-library",
"solana-labs/solana-accountsdb-plugin-postgres",
]

[[projects]]
name = "Spacemesh"
url = "https://github.com/spacemeshos"
repos = [
"spacemeshos/svm",
]

[[projects]]
name = "Subspace Labs"
url = "https://github.com/subspace"
repos = [
"subspace/subspace",
]

[[projects]]
name = "TezEdge"
url = "https://github.com/tezedge"
repos = [
"tezedge/tezedge",
"tezedge/tezedge-snapshots",
"tezedge/tezedge-tui",
]

[[projects]]
name = "Zcash"
url = "https://github.com/zcash"
repos = [
"ZcashFoundation/zebra",
"zcash/halo2",
"zcash/librustzcash",
]

[[projects]]
name = "zkSync"
url = "https://github.com/matter-labs/zksync"
repos = [
"matter-labs/zksync",
"matter-labs/compiler-solidity",
]
