[[projects]]
name = "CodeChain"
url = "https://github.com/CodeChain-io"
pull_merged_repos = [
  "nervosnetwork/ckb",
  "nervosnetwork/ckb-vm",
  "nervosnetwork/rfcs",
]

[[projects]]
name = "Nervos"
url = "https://github.com/nervosnetwork"
pull_merged_repos = [
  "nervosnetwork/ckb",
  "nervosnetwork/ckb-vm",
  "nervosnetwork/rfcs",
]

