# Projects are listed alphabetically.

[[projects]]
name = "Aleo"
url = "https://github.com/AleoHQ"
repos = [
"AleoHQ/aleo",
"AleoHQ/snarkOS",
"AleoHQ/leo",
]

[[projects]]
name = "CodeChain"
url = "https://github.com/CodeChain-io"
repos = [
"CodeChain-io/codechain",
"CodeChain-io/foundry",
"CodeChain-io/foundry-rpc-js",
"CodeChain-io/foundry-primitives-js",
"CodeChain-io/foundry-keystore-js",
"CodeChain-io/foundry-keystore-cli",
"CodeChain-io/foundry-sandbox",
]

[[projects]]
name = "COMIT"
url = "https://github.com/comit-network"
repos = [
"comit-network/comit-rs",
"comit-network/xmr-btc-swap",
"comit-network/create-comit-app",
"comit-network/blockchain-contracts",
]

[[projects]]
name = "Concordium"
url = "https://github.com/Concordium"
repos = [
"Concordium/concordium-node",
"Concordium/concordium-base",
"Concordium/concordium-contracts-common",
"Concordium/concordium-rust-smart-contracts",
]

[[projects]]
name = "Conflux"
url = "https://github.com/Conflux-Chain"
repos = [
"Conflux-Chain/conflux-rust",
]

[[projects]]
name = "Crypto.com Chain"
url = "https://github.com/crypto-com"
repos = [
"crypto-com/thaler",
]

[[projects]]
name = "Diem"
url = "https://github.com/diem"
repos = [
"diem/diem",
"diem/rosetta-proxy",
"diem/bcs",
]

[[projects]]
name = "Elrond"
url = "https://github.com/ElrondNetwork"
repos = [
"ElrondNetwork/sc-delegation-rs",
"ElrondNetwork/sc-band-bridge-rs",
"ElrondNetwork/mandos-rs",
"ElrondNetwork/elrond-wasm-rs",
"ElrondNetwork/sc-dns-rs",
]

[[projects]]
name = "Fluence"
url = "https://github.com/fluencelabs"
repos = [
"fluencelabs/fluence",
"fluencelabs/fce",
"fluencelabs/aquamarine",
"fluencelabs/rust-sdk",
]

[[projects]]
name = "Golem"
url = "https://github.com/golemfactory"
repos = [
"golemfactory/yagna",
"golemfactory/ya-client",
]

[[projects]]
name = "Grin"
url = "https://github.com/mimblewimble/grin"
repos = [
"mimblewimble/grin",
]

[[projects]]
name = "Holochain"
url = "https://github.com/holochain"
repos = [
"holochain/holochain-rust",
"holochain/holochain",
"holochain/elemental-chat",
"holochain/holochain-wasmer",
"holochain/lair",
]

[[projects]]
name = "Interledger"
url = "https://github.com/interledger-rs"
repos = [
"interledger-rs/interledger-rs",
]

[[projects]]
name = "Lighthouse"
url = "https://github.com/sigp/lighthouse"
repos = [
"sigp/lighthouse",
"sigp/beacon-fuzz",
"sigp/discv5",
]

[[projects]]
name = "MobileCoin"
url = "https://github.com/mobilecoinfoundation"
repos = [
"mobilecoinfoundation/mobilecoin",
]

[[projects]]
name = "NEAR"
url = "https://github.com/near/nearcore"
repos = [
"near/nearcore",
"near/borsh",
"near/core-contracts",
"near/near-evm",
]

[[projects]]
name = "Nervos"
url = "https://github.com/nervosnetwork"
repos = [
"nervosnetwork/ckb",
"nervosnetwork/ckb-vm",
"nervosnetwork/ckb-cli",
"nervosnetwork/capsule",
"nervosnetwork/ckb-std",
]

[[projects]]
name = "Oasis"
url = "https://github.com/oasislabs"
repos = [
"oasislabs/oasis-ethwasi-runtime",
"oasislabs/oasis-rs",
"oasislabs/oasis-cli",
"oasislabs/oasis-chain",
"oasisprotocol/deoxysii-rust",
]

[[projects]]
name = "Parity"
url = "https://github.com/paritytech"
repos = [
"paritytech/substrate",
"paritytech/polkadot",
"paritytech/cargo-contract",
"paritytech/wasmi",
"paritytech/parity-bitcoin",
"paritytech/cumulus",
"paritytech/ink",
]

[[projects]]
name = "Rust Bitcoin"
url = "https://github.com/rust-bitcoin"
repos = [
"rust-bitcoin/rust-bitcoin",
"rust-bitcoin/rust-lightning",
"rust-bitcoin/rust-miniscript",
"rust-bitcoin/rust-bitcoincore-rpc",
]

[[projects]]
name = "Rust Ethereum"
url = "https://github.com/rust-bitcoin"
repos = [
"rust-ethereum/ethabi",
"rust-ethereum/enr",
"rust-ethereum/devp2p",
"rust-ethereum/dnsdisc",
]

[[projects]]
name = "Secret Network"
url = "https://github.com/enigmampc"
repos = [
"enigmampc/SecretNetwork",
"enigmampc/secret-toolkit",
"enigmampc/SafeTrace",
]

[[projects]]
name = "Solana"
url = "https://github.com/solana-labs"
repos = [
"solana-labs/solana",
"solana-labs/solana-program-library",
]

[[projects]]
name = "Zcash"
url = "https://github.com/zcash"
repos = [
"ZcashFoundation/zebra",
"zcash/halo2",
"zcash/librustzcash",
]





